In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [8]:
def p_t(t, p_0):
    M = np.array([[2/3, 1/2], [1/3, 1/2]])
    res = np.matmul(np.linalg.matrix_power(M, t), p_0)
    return res

In [10]:
p_0 = np.array([1, 0])

print(p_t(1, p_0))
print(p_t(2, p_0))
print(p_t(3, p_0))
print(p_t(100, p_0))

[0.66666667 0.33333333]
[0.61111111 0.38888889]
[0.60185185 0.39814815]
[0.6 0.4]


In [11]:
p_0 = np.array([0, 1])

print(p_t(1, p_0))
print(p_t(2, p_0))
print(p_t(3, p_0))
print(p_t(100, p_0))

[0.5 0.5]
[0.58333333 0.41666667]
[0.59722222 0.40277778]
[0.6 0.4]


In [12]:
p_0 = np.array([0.6, 0.4])

print(p_t(1, p_0))
print(p_t(2, p_0))
print(p_t(3, p_0))
print(p_t(100, p_0))

[0.6 0.4]
[0.6 0.4]
[0.6 0.4]
[0.6 0.4]


In [16]:
p_0 = np.array([-1, 1])

print(p_t(1, p_0))
print(p_t(2, p_0))
print(p_t(3, p_0))
print(p_t(100, p_0))

for i in range(1, 20):
    ratio = p_t(i + 1, p_0) / p_t(i, p_0)
    print(ratio)

[-0.16666667  0.16666667]
[-0.02777778  0.02777778]
[-0.00462963  0.00462963]
[0. 0.]
[0.16666667 0.16666667]
[0.16666667 0.16666667]
[0.16666667 0.16666667]
[0.16666667 0.16666667]
[0.16666667 0.16666667]
[0.16666667 0.16666667]
[0.16666667 0.16666667]
[0.16666667 0.16666667]
[0.16666667 0.16666667]
[0.16666666 0.16666667]
[0.1666667  0.16666666]
[0.16666671 0.16666663]
[0.16666763 0.1666663 ]
[0.16666812 0.16666522]
[0.16667537 0.16667972]
[0.16661447 0.16677106]
[0.16729323 0.16619718]
[0.16853933 0.16384181]
[0.2        0.17241379]


In [23]:
def new_pt(t, gamma, e_1 = 1, e_2 = 1/6):
    a_1 = np.array([0.6, 0.4])
    a_2 = np.array([-1, 1])
    
    ans = a_1 + gamma * a_2 * (e_2 ** t)
    return ans

In [24]:
gamma = -0.4

print(new_pt(1, gamma))
print(new_pt(2, gamma))
print(new_pt(3, gamma))
print(new_pt(100, gamma))

[0.66666667 0.33333333]
[0.61111111 0.38888889]
[0.60185185 0.39814815]
[0.6 0.4]


In [45]:
def pagerank_vector(p_0, L, n):
    ans = np.matmul(np.linalg.matrix_power(L, n), p_0)
    return ans

In [48]:
p_01 = np.array([[0.05], [0.1], [0.01], [0.1], [0.74]])
p_02 = np.array([[0.03], [0.1], [0.01], [0.1], [0.76]])
p_03 = np.array([[0.2], [0.2], [0.2], [0.2], [0.2]])

L = np.array([[0.23, 0.05, 0.22, 0.26, 0.01],
             [0.25, 0.35, 0.32, 0.25, 0.34],
             [0.02, 0.03, 0.17, 0.3, 0.13],
             [0.23, 0.55, 0.18, 0.07, 0.3],
             [0.27, 0.02, 0.11, 0.12, 0.22]])

print(pagerank_vector(p_01, L, 1000))
print(pagerank_vector(p_02, L, 1000))
print(pagerank_vector(p_03, L, 100))

[[0.15562336]
 [0.30081549]
 [0.13634415]
 [0.28288532]
 [0.12433168]]
[[0.15562336]
 [0.30081549]
 [0.13634415]
 [0.28288532]
 [0.12433168]]
[[0.15562336]
 [0.30081549]
 [0.13634415]
 [0.28288532]
 [0.12433168]]
